#ifndef CODIGO_OPERACION_H_
#define CODIGO_OPERACION_H_

typedef enum
{
    HANDSHAKE = 1,
    ENVIO_PCB = 2,
    ENVIO_PID_PC = 3,
    ENVIO_PATH_INSTRUCCIONES = 4,
    INTERRUPCION = 5,
    FINALIZACION = 6,
    IO_GEN_SLEEP = 7,
    ENVIO_INTERRUPCION = 8,
    ENVIO_INTERFAZ_CONECTADA = 9
} t_codigo_operacion;

#endif