#ifndef CODIGO_OPERACION_H_
#define CODIGO_OPERACION_H_

#include "utils/codigo_error.h"
typedef enum
{
    HANDSHAKE = 1,
    ENVIO_PCB = 2,
    ENVIO_PID_PC = 3,
    ENVIO_PATH_INSTRUCCIONES = 4,
    INTERRUPCION = 5,
    FINALIZACION = 6,
    IO_GEN_SLEEP = 7,
    ENVIO_INTERRUPCION = 8,
    ENVIO_INTERFAZ_CONECTADA = 9,
    FINALIZAR_PROCESO_MEMORIA = 10,
    OBTENER_MARCO_MEMORIA = 11,
    RESIZE_MEMORIA = 12,
    ACCEDER_ESPACIO_DE_USUARIO_MEMORIA = 13,
    OBTENER_TAMANIO_PAGINA = 14,
    IO_STDIN_READ = 15,
    IO_STDOUT_WRITE = 16
} t_codigo_operacion;

#endif